// Code generated by protoc-gen-go.
// source: httprequest.proto
// DO NOT EDIT!

/*
Package transports is a generated protocol buffer package.

It is generated from these files:
	httprequest.proto
	httpresponse.proto

It has these top-level messages:
	HttpRequest
	HttpResponse
*/
package transports

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HttpRequest struct {
	Method           *string `protobuf:"bytes,1,req,name=method" json:"method,omitempty"`
	Url              *string `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	Proto            *string `protobuf:"bytes,3,req,name=proto" json:"proto,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HttpRequest) Reset()                    { *m = HttpRequest{} }
func (m *HttpRequest) String() string            { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()               {}
func (*HttpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HttpRequest) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *HttpRequest) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *HttpRequest) GetProto() string {
	if m != nil && m.Proto != nil {
		return *m.Proto
	}
	return ""
}

func init() {
	proto.RegisterType((*HttpRequest)(nil), "transports.HttpRequest")
}

var fileDescriptor0 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x28, 0x29, 0x29,
	0x28, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a,
	0x29, 0x4a, 0xcc, 0x2b, 0x2e, 0xc8, 0x2f, 0x2a, 0x29, 0x56, 0xb2, 0xe4, 0xe2, 0xf6, 0x00, 0x2a,
	0x08, 0x82, 0x28, 0x10, 0xe2, 0xe3, 0x62, 0xcb, 0x4d, 0x2d, 0xc9, 0xc8, 0x4f, 0x91, 0x60, 0x54,
	0x60, 0xd2, 0xe0, 0x14, 0xe2, 0xe6, 0x62, 0x2e, 0x2d, 0xca, 0x91, 0x60, 0x02, 0x73, 0x78, 0xb9,
	0x58, 0xc1, 0x06, 0x48, 0x30, 0x83, 0xb8, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90, 0x0c, 0x01,
	0xe5, 0x5a, 0x00, 0x00, 0x00,
}
